from __future__ import annotations
from typing import Protocol, Sequence, Optional
from uuid import UUID
from .entities import Project

class ProjectRepository(Protocol):
    async def add(self, project: Project) -> Project: ...
    async def get_by_id(self, *,owner_id: UUID,project_id: UUID) -> Optional[Project]: ...
    async def list_by_owner(self, owner_id: UUID) -> Sequence[Project]: ...
    async def delete(self, project_id: UUID) -> None: ...
