"""add embed_signature to chunk_embeddings

Revision ID: 089e4eb2fb0f
Revises: d397e72d05ee
Create Date: 2025-12-29 18:35:30.980226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '089e4eb2fb0f'
down_revision: Union[str, Sequence[str], None] = 'd397e72d05ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunk_embeddings', sa.Column('embed_signature', sa.String(length=64), nullable=False))
    op.drop_constraint(op.f('uq_chunk_embeddings_index_chunk'), 'chunk_embeddings', type_='unique')
    op.create_unique_constraint('uq_chunk_embeddings_index_chunk', 'chunk_embeddings', ['index_id', 'chunk_id', 'embed_signature'])
    op.create_index(op.f('ix_chunk_embeddings_embed_signature'), 'chunk_embeddings', ['embed_signature'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chunk_embeddings_embed_signature'), table_name='chunk_embeddings')
    op.drop_constraint('uq_chunk_embeddings_index_chunk', 'chunk_embeddings', type_='unique')
    op.create_unique_constraint(op.f('uq_chunk_embeddings_index_chunk'), 'chunk_embeddings', ['index_id', 'chunk_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('chunk_embeddings', 'embed_signature')
    # ### end Alembic commands ###
