"""init_schema_with_vector

Revision ID: 6691aa5d8877
Revises: 
Create Date: 2025-12-23 19:04:48.380514

"""
from typing import Sequence, Union

import pgvector
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6691aa5d8877'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # --- Manual Addition: Enable pgvector ---
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)

    op.create_table('projects',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('owner_id', sa.UUID(), nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('primary_document_id', sa.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='RESTRICT', initially='DEFERRED',
                                            deferrable=True),
                    # sa.ForeignKeyConstraint(['primary_document_id'], ['project_documents.id'], ondelete='RESTRICT',
                    #                         initially='DEFERRED', deferrable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('primary_document_id')
                    )
    op.create_index(op.f('ix_projects_owner_id'), 'projects', ['owner_id'], unique=False)

    op.create_table('project_documents',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('project_id', sa.UUID(), nullable=False),
                    sa.Column('original_filename', sa.String(length=512), nullable=False),
                    sa.Column('storage_path', sa.String(length=1024), nullable=False),
                    sa.Column('content_type', sa.String(length=128), nullable=False),
                    sa.Column('size_bytes', sa.Integer(), nullable=False),
                    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE', initially='DEFERRED',
                                            deferrable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('project_id'),
                    sa.UniqueConstraint('storage_path')
                    )

    op.create_foreign_key(
        'fk_projects_primary_document_id_project_documents',  # Name of the constraint
        'projects',  # Source table
        'project_documents',  # Target table
        ['primary_document_id'],  # Local column
        ['id'],  # Target column
        ondelete='RESTRICT',
        initially='DEFERRED',  # Important for your circular logic
        deferrable=True
    )


    op.create_table('document_indexes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'READY', 'FAILED', 'CANCELLED', name='index_status_enum', create_constraint=True), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('chunker_version', sa.String(length=64), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('embed_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('embed_signature', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_indexes_document_id'), 'document_indexes', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_indexes_project_id'), 'document_indexes', ['project_id'], unique=False)
    op.create_index(op.f('ix_document_indexes_status'), 'document_indexes', ['status'], unique=False)


    op.create_table('chunks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('index_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['index_id'], ['document_indexes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('index_id', 'chunk_index', name='uq_chunks_index_chunk_index')
    )
    op.create_index(op.f('ix_chunks_index_id'), 'chunks', ['index_id'], unique=False)

    op.create_table('chunk_embeddings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('index_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['index_id'], ['document_indexes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('index_id', 'chunk_id', name='uq_chunk_embeddings_index_chunk')
    )
    op.create_index(op.f('ix_chunk_embeddings_chunk_id'), 'chunk_embeddings', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_chunk_embeddings_chunk_index'), 'chunk_embeddings', ['chunk_index'], unique=False)
    op.create_index(op.f('ix_chunk_embeddings_index_id'), 'chunk_embeddings', ['index_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chunk_embeddings_index_id'), table_name='chunk_embeddings')
    op.drop_index(op.f('ix_chunk_embeddings_chunk_index'), table_name='chunk_embeddings')
    op.drop_index(op.f('ix_chunk_embeddings_chunk_id'), table_name='chunk_embeddings')
    op.drop_table('chunk_embeddings')
    op.drop_index(op.f('ix_chunks_index_id'), table_name='chunks')
    op.drop_table('chunks')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_projects_owner_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_table('project_documents')
    op.drop_index(op.f('ix_document_indexes_status'), table_name='document_indexes')
    op.drop_index(op.f('ix_document_indexes_project_id'), table_name='document_indexes')
    op.drop_index(op.f('ix_document_indexes_document_id'), table_name='document_indexes')
    op.drop_table('document_indexes')
    op.execute("DROP EXTENSION IF EXISTS vector")
    # ### end Alembic commands ###
