"""add_citations_to_chat_messages

Revision ID: 6a0872ef034f
Revises: 55004a34fc4e
Create Date: 2026-01-30 17:52:26.912014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6a0872ef034f'
down_revision: Union[str, Sequence[str], None] = '55004a34fc4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_index(op.f('ix_chats_owner_project_updated'), table_name='chats')
    op.create_index('ix_chats_owner_project_updated', 'chats', ['owner_id', 'project_id', sa.literal_column('updated_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chats_owner_project_updated', table_name='chats')
    op.create_index(op.f('ix_chats_owner_project_updated'), 'chats', ['owner_id', 'project_id', 'updated_at'], unique=False)
    op.drop_column('chat_messages', 'citations')
    # ### end Alembic commands ###
