"""add storage_path to document_indexes

Revision ID: d397e72d05ee
Revises: 6691aa5d8877
Create Date: 2025-12-26 20:53:36.357257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'd397e72d05ee'
down_revision: Union[str, Sequence[str], None] = '6691aa5d8877'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_indexes',
                  sa.Column(
        'storage_path',
        sa.String(),
        nullable=False,
        server_default="0",)
                  )
    op.alter_column(
        "document_indexes",
        "storage_path",
        server_default=None,  # optional cleanup
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_indexes', 'storage_path')
    # ### end Alembic commands ###
