"""Default (non-secret) configuration values used by BaseSettings."""

DEFAULT_SQLALCHEMY_DATABASE_URL = "postgresql+asyncpg://postgres:postgres@localhost:5432/talk_to_pdf"
DEFAULT_TEST_SQLALCHEMY_DATABASE_URL = "postgresql+asyncpg://postgres:postgres@localhost:5432/talk_to_pdf_test"

DEFAULT_JWT_SECRET_KEY = "change-me"
DEFAULT_JWT_ALGORITHM = "HS256"
DEFAULT_SKIP_AUTH = False
DEFAULT_FILE_STORAGE_DIR = "tmpstorage"

DEFAULT_EMBED_PROVIDER = "openai"
DEFAULT_EMBED_MODEL = "text-embedding-3-small"
DEFAULT_EMBED_BATCH_SIZE = 16
DEFAULT_EMBED_DIMENSIONS = None

DEFAULT_CHUNKER_KIND = "block"
DEFAULT_CHUNKER_MAX_CHARS = 1200
DEFAULT_CHUNKER_OVERLAP = 200

DEFAULT_MAX_TOP_K = 20
DEFAULT_MAX_TOP_N = 5

DEFAULT_REPLY_PROVIDER = "openai"
DEFAULT_REPLY_MODEL = "gpt-4o-mini"
DEFAULT_REPLY_TEMPERATURE = 0.2
DEFAULT_REPLY_MAX_OUTPUT_TOKENS = None
DEFAULT_REPLY_MAX_CONTEXT_CHARS = 20000

DEFAULT_QUERY_REWRITER_PROVIDER = "openai"
DEFAULT_QUERY_REWRITER_MODEL = "gpt-4o-mini"
DEFAULT_QUERY_REWRITER_TEMPERATURE = 0.2
DEFAULT_QUERY_REWRITER_MAX_TURN = 6
DEFAULT_QUERY_REWRITER_MAX_HISTORY_CHARS = 6000

DEFAULT_GROBID_URL = "http://grobid:8070"

DEFAULT_RERANKER_PROVIDER = "openai"
DEFAULT_RERANKER_MODEL = "gpt-4o-mini"
DEFAULT_RERANKER_TEMPERATURE = 0.0
