from logging.config import fileConfig
from sqlalchemy import engine_from_config
from sqlalchemy import pool
from alembic import context
from dotenv import load_dotenv
load_dotenv()
# 1. Import your Base and Models
# (Importing models ensures they are registered with Base.metadata)
from talk_to_pdf.backend.app.infrastructure.db.base import Base
import talk_to_pdf.backend.app.infrastructure.db.models

# 2. Set the target metadata
target_metadata = Base.metadata

config = context.config


# 3. Your URL helper function
def get_url() -> str:
    # Retrieve the URL from alembic.ini or env vars
    url = config.get_main_option("sqlalchemy.url")
    if url is None:
        # Fallback if you use env vars directly not in alembic.ini
        import os
        url = os.getenv("SQLALCHEMY_DATABASE_URL")

    if url is None:
        raise RuntimeError("DATABASE_URL must be set")

    # Force sync driver for Alembic (assumes you have psycopg2 installed)
    return url.replace("+asyncpg", "")


def run_migrations_online() -> None:
    """Run migrations in 'online' mode."""

    # Overwrite the sqlalchemy.url in the config object
    configuration = config.get_section(config.config_ini_section)
    configuration["sqlalchemy.url"] = get_url()

    connectable = engine_from_config(
        configuration,
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            # This helps nicely format the autogenerated code
            compare_type=True
        )

        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    # Handle offline mode if needed, similar to online but without engine
    url = get_url()
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()
else:
    run_migrations_online()